In [3]:
import pandas as pd

data = pd.read_csv("aggregated_2021.csv")

In [4]:

data_replaced = data.replace("", pd.NA)

count_non_blank = data_replaced.groupby('state').count().reset_index()

count_non_blank

                  state  Earthquake  fire  radio  Hurricane  flood
0               Alabama           4     2      2         32     12
1                Alaska           6     1      1          1      2
2               Arizona          36    23      3         32     29
3              Arkansas           1     1      0          4      9
4            California         290   182     30         42     91
5              Colorado           6     9      2          2     12
6           Connecticut           5     1      1         14      2
7              Delaware           1     1      0          2      2
8               Florida          52    31      7        335     88
9               Georgia          11     2      0         25     21
10               Hawaii          15     4      0         22     16
11                Idaho           1     2      0          0      3
12             Illinois          16     5      3         10     33
13              Indiana           6     1      4          5     11
14                 Iowa           0     2      0          3      7
15               Kansas           3     5      1          2      9
16             Kentucky           1     3      0          5     15
17            Louisiana           6     5      5         50     34
18                Maine           2     0      0          4      6
19             Maryland          10     1      3         13     10
20        Massachusetts          10     0      1         14      5
21             Michigan           6     1      1          2     12
22            Minnesota           2     0      0          0      7
23          Mississippi           3     0      0         13      5
24             Missouri           7     1      0          1     16
25              Montana           0     1      0          0      2
26             Nebraska           0     0      0          2      5
27               Nevada           6     4      0          3      3
28        New Hampshire           1     0      0          1      2
29           New Jersey          13     8      9         49     29
30           New Mexico           4     4      0          4      4
31             New York          62    22     19         96     78
32       North Carolina           6     5      2         50     20
33         North Dakota           0     0      1          0      2
34                 Ohio           5     3      3          8     16
35             Oklahoma           5     2      0          1      6
36               Oregon          36    65      3          9     22
37         Pennsylvania          13     6      7         21     23
38          Puerto Rico          25     2      0         46      9
39         Rhode Island           2     0      0          5      3
40       South Carolina           2     3      1         20     14
41         South Dakota           0     1      0          0      2
42            Tennessee           3     5      0          4     16
43                Texas          35    22     10        144    112
44  U.S. Virgin Islands           1     0      0          1      0
45                 Utah          14     6      0          0      3
46              Vermont           0     0      0          1      0
47             Virginia          12     3      2         25     11
48           Washington          84    51      4         25     43
49     Washington, D.C.           1     0      3          0      0
50        West Virginia           1     2      0          1      7
51            Wisconsin           4     2      0          1      6
52              Wyoming           0     0      0          0      0

In [6]:


state_coordinates = {
    "Alabama": {"latitude": 32.806671, "longitude": -86.791130},
    "Alaska": {"latitude": 61.370716, "longitude": -152.404419},
    "Arizona": {"latitude": 33.729759, "longitude": -111.431221},
    "Arkansas": {"latitude": 34.969704, "longitude": -92.373123},
    "California": {"latitude": 36.116203, "longitude": -119.681564},

}


coordinates_df = pd.DataFrame(state_coordinates).T.reset_index()
coordinates_df.columns = ['state', 'latitude', 'longitude']

merged_data = pd.merge(count_non_blank, coordinates_df, on='state', how='left')

merged_data.head()

extended_state_coordinates = {

        "Alabama": {"latitude": 32.806671, "longitude": -86.791130},
    "Alaska": {"latitude": 61.370716, "longitude": -152.404419},
    "Arizona": {"latitude": 33.729759, "longitude": -111.431221},
    "Arkansas": {"latitude": 34.969704, "longitude": -92.373123},
    "California": {"latitude": 36.116203, "longitude": -119.681564},

    "Colorado": {"latitude": 39.059811, "longitude": -105.311104},
    "Connecticut": {"latitude": 41.597782, "longitude": -72.755371},
    "Delaware": {"latitude": 39.318523, "longitude": -75.507141},
    "Florida": {"latitude": 27.766279, "longitude": -81.686783},
    "Georgia": {"latitude": 33.040619, "longitude": -83.643074},
    "Hawaii": {"latitude": 21.094318, "longitude": -157.498337},
    "Idaho": {"latitude": 44.240459, "longitude": -114.478828},
    "Illinois": {"latitude": 40.349457, "longitude": -88.986137},
    "Indiana": {"latitude": 39.849426, "longitude": -86.258278},
    "Iowa": {"latitude": 42.011539, "longitude": -93.210526},
    "Kansas": {"latitude": 38.526600, "longitude": -96.726486},
    "Kentucky": {"latitude": 37.668140, "longitude": -84.670067},
    "Louisiana": {"latitude": 31.169546, "longitude": -91.867805},
    "Maine": {"latitude": 44.693947, "longitude": -69.381927},
    "Maryland": {"latitude": 39.063946, "longitude": -76.802101},
    "Massachusetts": {"latitude": 42.230171, "longitude": -71.530106},
    "Michigan": {"latitude": 43.326618, "longitude": -84.536095},
    "Minnesota": {"latitude": 45.694454, "longitude": -93.900192},
    "Mississippi": {"latitude": 32.741646, "longitude": -89.678696},
    "Missouri": {"latitude": 38.456085, "longitude": -92.288368},
    "Montana": {"latitude": 46.921925, "longitude": -110.454353},
    "Nebraska": {"latitude": 41.125370, "longitude": -98.268082},
    "Nevada": {"latitude": 38.313515, "longitude": -117.055374},
    "New Hampshire": {"latitude": 43.452492, "longitude": -71.563896},
    "New Jersey": {"latitude": 40.298904, "longitude": -74.521011},
    "New Mexico": {"latitude": 34.840515, "longitude": -106.248482},
    "New York": {"latitude": 42.165726, "longitude": -74.948051},
    "North Carolina": {"latitude": 35.630066, "longitude": -79.806419},
    "North Dakota": {"latitude": 47.528912, "longitude": -99.784012},
    "Ohio": {"latitude": 40.388783, "longitude": -82.764915},
    "Oklahoma": {"latitude": 35.565342, "longitude": -96.928917},
    "Oregon": {"latitude": 44.572021, "longitude": -122.070938},
    "Pennsylvania": {"latitude": 40.590752, "longitude": -77.209755},
    "Puerto Rico": {"latitude": 18.220833, "longitude": -66.590149},
    "Rhode Island": {"latitude": 41.680893, "longitude": -71.511780},
    "South Carolina": {"latitude": 33.856892, "longitude": -80.945007},
    "South Dakota": {"latitude": 44.299782, "longitude": -99.438828},
    "Tennessee": {"latitude": 35.747845, "longitude": -86.692345},
    "Texas": {"latitude": 31.054487, "longitude": -97.563461},
    "U.S. Virgin Islands": {"latitude": 18.335765, "longitude": -64.896335},
    "Utah": {"latitude": 40.150032, "longitude": -111.862434},
    "Vermont": {"latitude": 44.045876, "longitude": -72.710686},
    "Virginia": {"latitude": 37.769337, "longitude": -78.169968},
    "Washington": {"latitude": 47.400902, "longitude": -121.490494},
    "Washington, D.C.": {"latitude": 38.897438, "longitude": -77.026817},
    "West Virginia": {"latitude": 38.491226, "longitude": -80.954455},
    "Wisconsin": {"latitude": 44.268543, "longitude": -89.616508},
    "Wyoming": {"latitude": 42.755966, "longitude": -107.302490},
}


extended_coordinates_df = pd.DataFrame(extended_state_coordinates).T.reset_index()
extended_coordinates_df.columns = ['state', 'latitude', 'longitude']

full_merged_data = pd.merge(count_non_blank, extended_coordinates_df, on='state', how='left')

In [7]:
full_merged_data.to_csv("aggregated_2021.csv")